"""calendar items publishing slots and recommendations

Revision ID: 1b3ffc9cdd9d
Revises: 5b0d2177602d
Create Date: 2026-08-21 00:07:59.483044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1b3ffc9cdd9d'
down_revision: Union[str, None] = '5b0d2177602d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar_recommendations',
    sa.Column('channel_id', sa.UUID(), nullable=False),
    sa.Column('balance_report_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('conflicts_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('generated_by_agent_run_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calendar_recommendations_organization_id'), 'calendar_recommendations', ['organization_id'], unique=False)
    op.create_table('publishing_slots',
    sa.Column('channel_id', sa.UUID(), nullable=False),
    sa.Column('day_of_week', sa.Enum('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY', name='day_of_week', native_enum=False), nullable=False),
    sa.Column('local_time', sa.Time(), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('content_type', sa.Enum('SHORT', 'LONG_FORM', 'LIVE', 'UNKNOWN', name='source_video_type', native_enum=False), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publishing_slots_organization_id'), 'publishing_slots', ['organization_id'], unique=False)
    op.create_table('calendar_items',
    sa.Column('channel_id', sa.UUID(), nullable=False),
    sa.Column('idea_id', sa.UUID(), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('calendar_recommendation_id', sa.UUID(), nullable=True),
    sa.Column('content_type', sa.Enum('SHORT', 'LONG_FORM', 'LIVE', 'UNKNOWN', name='source_video_type', native_enum=False), nullable=False),
    sa.Column('planned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('SUGGESTED', 'PLANNED', 'APPROVED', 'PRODUCING', 'READY', 'SCHEDULED', 'PUBLISHED', 'CANCELLED', name='calendar_item_status', native_enum=False), nullable=False),
    sa.Column('source', sa.Enum('AI', 'USER', name='calendar_item_source', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['calendar_recommendation_id'], ['calendar_recommendations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['idea_id'], ['content_ideas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calendar_items_organization_id'), 'calendar_items', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_calendar_items_organization_id'), table_name='calendar_items')
    op.drop_table('calendar_items')
    op.drop_index(op.f('ix_publishing_slots_organization_id'), table_name='publishing_slots')
    op.drop_table('publishing_slots')
    op.drop_index(op.f('ix_calendar_recommendations_organization_id'), table_name='calendar_recommendations')
    op.drop_table('calendar_recommendations')
    # ### end Alembic commands ###
