"""youtube channel connections

Revision ID: 59037a0445d8
Revises: 373efef0edb5
Create Date: 2026-08-20 13:19:23.959968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '59037a0445d8'
down_revision: Union[str, None] = '373efef0edb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel_connections',
    sa.Column('channel_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.Enum('GOOGLE_YOUTUBE', name='channel_connection_provider', native_enum=False), nullable=False),
    sa.Column('external_account_id', sa.String(length=128), nullable=True),
    sa.Column('access_token_encrypted', sa.String(length=2000), nullable=False),
    sa.Column('refresh_token_encrypted', sa.String(length=2000), nullable=False),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scopes', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('status', sa.Enum('CONNECTED', 'NEEDS_REAUTHORIZATION', 'SYNCING', 'ERROR', 'DISCONNECTED', name='channel_connection_status', native_enum=False), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id', 'provider', name='uq_channel_connections_channel_provider')
    )
    op.create_index(op.f('ix_channel_connections_organization_id'), 'channel_connections', ['organization_id'], unique=False)
    op.create_table('channel_sync_runs',
    sa.Column('channel_id', sa.UUID(), nullable=False),
    sa.Column('sync_type', sa.Enum('INITIAL', 'FULL', 'INCREMENTAL', 'MANUAL', name='sync_type', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='sync_run_status', native_enum=False), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('items_discovered', sa.Integer(), nullable=False),
    sa.Column('items_created', sa.Integer(), nullable=False),
    sa.Column('items_updated', sa.Integer(), nullable=False),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.String(length=2000), nullable=True),
    sa.Column('correlation_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_channel_sync_runs_correlation_id'), 'channel_sync_runs', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_channel_sync_runs_organization_id'), 'channel_sync_runs', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_channel_sync_runs_organization_id'), table_name='channel_sync_runs')
    op.drop_index(op.f('ix_channel_sync_runs_correlation_id'), table_name='channel_sync_runs')
    op.drop_table('channel_sync_runs')
    op.drop_index(op.f('ix_channel_connections_organization_id'), table_name='channel_connections')
    op.drop_table('channel_connections')
    # ### end Alembic commands ###
