"""content ideas opportunities and scoring

Revision ID: 5b0d2177602d
Revises: c47ddb8e1d69
Create Date: 2026-08-20 21:04:58.938512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5b0d2177602d'
down_revision: Union[str, None] = 'c47ddb8e1d69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_clusters',
    sa.Column('channel_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('topic', sa.String(length=200), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'ARCHIVED', name='content_cluster_status', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_clusters_organization_id'), 'content_clusters', ['organization_id'], unique=False)
    op.create_table('content_ideas',
    sa.Column('channel_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('idea_type', sa.String(length=100), nullable=True),
    sa.Column('origin', sa.Enum('AI', 'TREND', 'USER', 'ANALYTICS', 'SERIES', 'REPURPOSE', name='idea_origin', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'EVALUATING', 'RECOMMENDED', 'APPROVED', 'REJECTED', 'ARCHIVED', name='idea_status', native_enum=False), nullable=False),
    sa.Column('recommended_format', sa.String(length=50), nullable=True),
    sa.Column('generated_by_agent_run_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_ideas_organization_id'), 'content_ideas', ['organization_id'], unique=False)
    op.create_table('content_opportunities',
    sa.Column('channel_id', sa.UUID(), nullable=False),
    sa.Column('idea_id', sa.UUID(), nullable=False),
    sa.Column('opportunity_score', sa.Float(), nullable=False),
    sa.Column('recommended_format', sa.String(length=50), nullable=True),
    sa.Column('recommended_duration', sa.Integer(), nullable=True),
    sa.Column('recommended_publish_window', sa.String(length=100), nullable=True),
    sa.Column('reasoning_summary', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('RECOMMENDED', 'REJECTED', name='opportunity_status', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['idea_id'], ['content_ideas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_opportunities_organization_id'), 'content_opportunities', ['organization_id'], unique=False)
    op.create_table('idea_relationships',
    sa.Column('idea_id', sa.UUID(), nullable=False),
    sa.Column('related_idea_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.Enum('PARENT', 'CHILD', 'RELATED', 'REPURPOSE', 'SEQUEL', 'SERIES', name='idea_relationship_type', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['idea_id'], ['content_ideas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['related_idea_id'], ['content_ideas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idea_id', 'related_idea_id', 'relationship_type', name='uq_idea_relationships_pair')
    )
    op.create_index(op.f('ix_idea_relationships_organization_id'), 'idea_relationships', ['organization_id'], unique=False)
    op.create_table('opportunity_scores',
    sa.Column('opportunity_id', sa.UUID(), nullable=False),
    sa.Column('score_type', sa.Enum('CHANNEL_FIT', 'AUDIENCE_FIT', 'TREND', 'NOVELTY', 'RETENTION_POTENTIAL', 'SEARCH_POTENTIAL', 'COMPETITION', 'BRAND_FIT', 'STRATEGIC_FIT', name='score_type', native_enum=False), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('weighted_score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['content_opportunities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opportunity_scores_organization_id'), 'opportunity_scores', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_opportunity_scores_organization_id'), table_name='opportunity_scores')
    op.drop_table('opportunity_scores')
    op.drop_index(op.f('ix_idea_relationships_organization_id'), table_name='idea_relationships')
    op.drop_table('idea_relationships')
    op.drop_index(op.f('ix_content_opportunities_organization_id'), table_name='content_opportunities')
    op.drop_table('content_opportunities')
    op.drop_index(op.f('ix_content_ideas_organization_id'), table_name='content_ideas')
    op.drop_table('content_ideas')
    op.drop_index(op.f('ix_content_clusters_organization_id'), table_name='content_clusters')
    op.drop_table('content_clusters')
    # ### end Alembic commands ###
