"""channel dna and brand profiles

Revision ID: 8c4e080a0b01
Revises: af40e97c1986
Create Date: 2026-08-20 18:35:39.444387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8c4e080a0b01'
down_revision: Union[str, None] = 'af40e97c1986'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brand_profiles',
    sa.Column('channel_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('colors_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('typography_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('visual_style_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tone_of_voice_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rules_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('prohibited_elements_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id', name='uq_brand_profiles_channel_id')
    )
    op.create_index(op.f('ix_brand_profiles_organization_id'), 'brand_profiles', ['organization_id'], unique=False)
    op.create_table('channel_dna_versions',
    sa.Column('channel_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'SUPERSEDED', name='channel_dna_status', native_enum=False), nullable=False),
    sa.Column('classification_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('audience_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('formats_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('content_patterns_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('performance_patterns_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('brand_rules_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('publishing_patterns_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('restrictions_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recommendations_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('generated_by_agent_run_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id', 'version', name='uq_channel_dna_versions_channel_version')
    )
    op.create_index(op.f('ix_channel_dna_versions_organization_id'), 'channel_dna_versions', ['organization_id'], unique=False)
    op.create_index('uq_channel_dna_versions_one_active_per_channel', 'channel_dna_versions', ['channel_id'], unique=True, postgresql_where="status = 'active'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_channel_dna_versions_one_active_per_channel', table_name='channel_dna_versions', postgresql_where="status = 'active'")
    op.drop_index(op.f('ix_channel_dna_versions_organization_id'), table_name='channel_dna_versions')
    op.drop_table('channel_dna_versions')
    op.drop_index(op.f('ix_brand_profiles_organization_id'), table_name='brand_profiles')
    op.drop_table('brand_profiles')
    # ### end Alembic commands ###
