"""source videos playlists metrics

Revision ID: 93a5b4b81649
Revises: 59037a0445d8
Create Date: 2026-08-20 17:40:39.079997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '93a5b4b81649'
down_revision: Union[str, None] = '59037a0445d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source_playlists',
    sa.Column('channel_id', sa.UUID(), nullable=False),
    sa.Column('external_playlist_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('item_count', sa.Integer(), nullable=False),
    sa.Column('raw_metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id', 'external_playlist_id', name='uq_source_playlists_channel_external_id')
    )
    op.create_index(op.f('ix_source_playlists_organization_id'), 'source_playlists', ['organization_id'], unique=False)
    op.create_table('source_videos',
    sa.Column('channel_id', sa.UUID(), nullable=False),
    sa.Column('external_video_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('video_type', sa.Enum('SHORT', 'LONG_FORM', 'LIVE', 'UNKNOWN', name='source_video_type', native_enum=False), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('privacy_status', sa.String(length=50), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=1000), nullable=True),
    sa.Column('raw_metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id', 'external_video_id', name='uq_source_videos_channel_external_id')
    )
    op.create_index(op.f('ix_source_videos_organization_id'), 'source_videos', ['organization_id'], unique=False)
    op.create_table('source_video_metrics',
    sa.Column('channel_id', sa.UUID(), nullable=False),
    sa.Column('source_video_id', sa.UUID(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('views', sa.BigInteger(), nullable=True),
    sa.Column('likes', sa.BigInteger(), nullable=True),
    sa.Column('comments', sa.BigInteger(), nullable=True),
    sa.Column('watch_time_minutes', sa.Float(), nullable=True),
    sa.Column('average_view_duration', sa.Float(), nullable=True),
    sa.Column('average_view_percentage', sa.Float(), nullable=True),
    sa.Column('subscribers_gained', sa.Integer(), nullable=True),
    sa.Column('subscribers_lost', sa.Integer(), nullable=True),
    sa.Column('impressions', sa.BigInteger(), nullable=True),
    sa.Column('impressions_ctr', sa.Float(), nullable=True),
    sa.Column('raw_metrics_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_video_id'], ['source_videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_video_id', 'captured_at', name='uq_source_video_metrics_video_captured_at')
    )
    op.create_index(op.f('ix_source_video_metrics_organization_id'), 'source_video_metrics', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_source_video_metrics_organization_id'), table_name='source_video_metrics')
    op.drop_table('source_video_metrics')
    op.drop_index(op.f('ix_source_videos_organization_id'), table_name='source_videos')
    op.drop_table('source_videos')
    op.drop_index(op.f('ix_source_playlists_organization_id'), table_name='source_playlists')
    op.drop_table('source_playlists')
    # ### end Alembic commands ###
