"""channel and audience profiles

Revision ID: af40e97c1986
Revises: 93a5b4b81649
Create Date: 2026-08-20 18:16:43.838886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'af40e97c1986'
down_revision: Union[str, None] = '93a5b4b81649'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audience_profiles',
    sa.Column('channel_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('profile_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source', sa.Enum('YOUTUBE', 'USER', 'INFERRED', 'MIXED', name='audience_profile_source', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id', 'version', name='uq_audience_profiles_channel_version')
    )
    op.create_index(op.f('ix_audience_profiles_organization_id'), 'audience_profiles', ['organization_id'], unique=False)
    op.create_table('channel_profiles',
    sa.Column('channel_id', sa.UUID(), nullable=False),
    sa.Column('primary_language', sa.String(length=16), nullable=True),
    sa.Column('primary_category', sa.String(length=200), nullable=True),
    sa.Column('estimated_audience', sa.String(length=500), nullable=True),
    sa.Column('content_summary', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id', name='uq_channel_profiles_channel_id')
    )
    op.create_index(op.f('ix_channel_profiles_organization_id'), 'channel_profiles', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_channel_profiles_organization_id'), table_name='channel_profiles')
    op.drop_table('channel_profiles')
    op.drop_index(op.f('ix_audience_profiles_organization_id'), table_name='audience_profiles')
    op.drop_table('audience_profiles')
    # ### end Alembic commands ###
