"""content strategies pillars and rules

Revision ID: c47ddb8e1d69
Revises: 8c4e080a0b01
Create Date: 2026-08-20 20:16:06.454671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c47ddb8e1d69'
down_revision: Union[str, None] = '8c4e080a0b01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_strategies',
    sa.Column('channel_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'ARCHIVED', name='content_strategy_status', native_enum=False), nullable=False),
    sa.Column('objective', sa.String(length=1000), nullable=False),
    sa.Column('shorts_ratio', sa.Float(), nullable=False),
    sa.Column('long_form_ratio', sa.Float(), nullable=False),
    sa.Column('experimental_ratio', sa.Float(), nullable=False),
    sa.Column('recommended_frequency_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('strategy_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('generated_by_agent_run_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id', 'version', name='uq_content_strategies_channel_version')
    )
    op.create_index(op.f('ix_content_strategies_organization_id'), 'content_strategies', ['organization_id'], unique=False)
    op.create_index('uq_content_strategies_one_active_per_channel', 'content_strategies', ['channel_id'], unique=True, postgresql_where="status = 'active'")
    op.create_table('content_pillars',
    sa.Column('channel_id', sa.UUID(), nullable=False),
    sa.Column('strategy_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('target_ratio', sa.Float(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['strategy_id'], ['content_strategies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_pillars_organization_id'), 'content_pillars', ['organization_id'], unique=False)
    op.create_table('strategy_rules',
    sa.Column('strategy_id', sa.UUID(), nullable=False),
    sa.Column('rule_type', sa.String(length=100), nullable=False),
    sa.Column('rule_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['strategy_id'], ['content_strategies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategy_rules_organization_id'), 'strategy_rules', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_strategy_rules_organization_id'), table_name='strategy_rules')
    op.drop_table('strategy_rules')
    op.drop_index(op.f('ix_content_pillars_organization_id'), table_name='content_pillars')
    op.drop_table('content_pillars')
    op.drop_index('uq_content_strategies_one_active_per_channel', table_name='content_strategies', postgresql_where="status = 'active'")
    op.drop_index(op.f('ix_content_strategies_organization_id'), table_name='content_strategies')
    op.drop_table('content_strategies')
    # ### end Alembic commands ###
